# 是否仅允许主人使用，true 表示只有主人可以使用插件
isMasterUse: false

# 是否允许私聊使用，true 表示用户可以在私聊中使用插件
allowPM: true

# 每名用户每日搜索次数限制，超过限制将无法继续使用
limit: 30

# 绕过 Cloudflare Challenge 所使用的 TLS 版本，推荐 TLSv1.2
cfTLSVersion: TLSv1.2
